
-- FOREIGN KEYS
ALTER TABLE public.banners ADD CONSTRAINT banners_segment_exclude_product_id_fkey FOREIGN KEY (segment_exclude_product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.community_comments ADD CONSTRAINT community_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.community_comments(id) ON DELETE CASCADE;
ALTER TABLE public.community_comments ADD CONSTRAINT community_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.community_posts(id) ON DELETE CASCADE;
ALTER TABLE public.community_likes ADD CONSTRAINT community_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.community_posts(id) ON DELETE CASCADE;
ALTER TABLE public.community_posts ADD CONSTRAINT community_posts_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.course_enrollments ADD CONSTRAINT course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.course_lessons ADD CONSTRAINT course_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.course_modules(id) ON DELETE CASCADE;
ALTER TABLE public.course_modules ADD CONSTRAINT course_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.courses ADD CONSTRAINT courses_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.course_categories(id) ON DELETE SET NULL;
ALTER TABLE public.diagnostic_answers ADD CONSTRAINT diagnostic_answers_diagnostic_id_fkey FOREIGN KEY (diagnostic_id) REFERENCES public.diagnostics(id) ON DELETE CASCADE;
ALTER TABLE public.diagnostic_answers ADD CONSTRAINT diagnostic_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.diagnostic_questions(id) ON DELETE CASCADE;
ALTER TABLE public.diagnostic_lead_tracking ADD CONSTRAINT diagnostic_lead_tracking_diagnostic_id_fkey FOREIGN KEY (diagnostic_id) REFERENCES public.diagnostics(id) ON DELETE CASCADE;
ALTER TABLE public.diagnostic_recommendation_rules ADD CONSTRAINT diagnostic_recommendation_rules_recommended_product_id_fkey FOREIGN KEY (recommended_product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_comments ADD CONSTRAINT lesson_comments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_comments ADD CONSTRAINT lesson_comments_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_comments ADD CONSTRAINT lesson_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.lesson_comments(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_contents ADD CONSTRAINT lesson_contents_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_progress ADD CONSTRAINT lesson_progress_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_progress ADD CONSTRAINT lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_ratings ADD CONSTRAINT lesson_ratings_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.lesson_ratings ADD CONSTRAINT lesson_ratings_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(id) ON DELETE CASCADE;
ALTER TABLE public.menu_link_packages ADD CONSTRAINT menu_link_packages_menu_link_id_fkey FOREIGN KEY (menu_link_id) REFERENCES public.menu_links(id) ON DELETE CASCADE;
ALTER TABLE public.menu_link_packages ADD CONSTRAINT menu_link_packages_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;
ALTER TABLE public.menu_link_products ADD CONSTRAINT menu_link_products_menu_link_id_fkey FOREIGN KEY (menu_link_id) REFERENCES public.menu_links(id) ON DELETE CASCADE;
ALTER TABLE public.menu_link_products ADD CONSTRAINT menu_link_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.offers ADD CONSTRAINT offers_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;
ALTER TABLE public.offers ADD CONSTRAINT offers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.package_product_groups ADD CONSTRAINT package_product_groups_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;
ALTER TABLE public.package_products ADD CONSTRAINT package_products_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.package_product_groups(id) ON DELETE SET NULL;
ALTER TABLE public.package_products ADD CONSTRAINT package_products_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;
ALTER TABLE public.package_products ADD CONSTRAINT package_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.plan_courses ADD CONSTRAINT plan_courses_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
ALTER TABLE public.plan_courses ADD CONSTRAINT plan_courses_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id) ON DELETE CASCADE;
ALTER TABLE public.plan_meetings ADD CONSTRAINT plan_meetings_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;
ALTER TABLE public.plan_services ADD CONSTRAINT plan_services_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id) ON DELETE CASCADE;
ALTER TABLE public.plan_services ADD CONSTRAINT plan_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE;
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.course_categories(id) ON DELETE CASCADE;
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.product_sales_pages ADD CONSTRAINT product_sales_pages_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE SET NULL;
ALTER TABLE public.user_lesson_access ADD CONSTRAINT user_lesson_access_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.course_lessons(id) ON DELETE CASCADE;
ALTER TABLE public.user_plans ADD CONSTRAINT user_plans_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id);
ALTER TABLE public.user_plans ADD CONSTRAINT user_plans_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;
ALTER TABLE public.user_products ADD CONSTRAINT user_products_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id);
ALTER TABLE public.user_products ADD CONSTRAINT user_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

-- INDEXES
CREATE INDEX idx_community_comments_post ON public.community_comments USING btree (post_id, created_at);
CREATE INDEX idx_community_likes_post ON public.community_likes USING btree (post_id);
CREATE INDEX idx_community_posts_course ON public.community_posts USING btree (course_id, created_at DESC);
CREATE INDEX idx_system_logs_created_at ON public.system_logs USING btree (created_at DESC);
CREATE INDEX idx_system_logs_entity_type ON public.system_logs USING btree (entity_type);
CREATE INDEX idx_system_logs_level ON public.system_logs USING btree (level);

-- RLS ENABLE
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnostic_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnostic_lead_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnostic_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnostic_recommendation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnostics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_link_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_link_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.network_topologies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_product_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_sales_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_lesson_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_endpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_event_types ENABLE ROW LEVEL SECURITY;
