// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tquqsqslaukdlohyeicc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdXFzcXNsYXVrZGxvaHllaWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNTc2ODgsImV4cCI6MjA4ODYzMzY4OH0.MvhqC5ADwGChWOdRA0eYv_g2-eZBxT_1s1b5PgcPFJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});